# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_savedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('article', 'Հոդված'), ('news', 'Նորություն')], default='news', max_length=50),
            preserve_default=False,
        ),
    ]
