# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('keywords', models.TextField()),
                ('abbr_arm', models.CharField(blank=True, max_length=200)),
                ('abbr_eng', models.CharField(blank=True, max_length=200)),
                ('title_eng', models.CharField(max_length=200)),
                ('randomizer', models.IntegerField()),
                ('related_topics', models.ManyToManyField(blank=True, related_name='_topic_related_topics_+', to='topics.Topic')),
            ],
        ),
    ]
