# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-02 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='keywords',
            field=models.CharField(default='', max_length=350),
            preserve_default=False,
        ),
    ]
