# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-02 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topic_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
