# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-05 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20170205_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='keywords',
            field=models.CharField(max_length=1000),
        ),
    ]
