# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-05 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_auto_20170205_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='keywords',
            field=models.TextField(),
        ),
    ]
