# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_auto_20170205_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='related_topics',
            field=models.ManyToManyField(blank=True, related_name='_topic_related_topics_+', to='topics.Topic'),
        ),
    ]
