# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_topic_related_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='abbr_arm',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
