# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_topic_abbr_arm'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='abbr_eng',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
