# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_topic_abbr_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='title_eng',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
