# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-02 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20170202_1532'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='topics',
            field=models.ManyToManyField(to='topics.Topic'),
        ),
    ]
