# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-02 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='topics',
            field=models.ManyToManyField(blank=True, null=True, to='topics.Topic'),
        ),
    ]
