# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-02 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0001_initial'),
        ('accounts', '0003_auto_20170202_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='magazines',
            field=models.ManyToManyField(blank=True, null=True, to='magazines.Magazine'),
        ),
    ]
