# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-07 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_views'),
        ('accounts', '0004_user_magazines'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_articles',
            field=models.ManyToManyField(to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='user',
            name='magazines',
            field=models.ManyToManyField(blank=True, to='magazines.Magazine'),
        ),
    ]
