# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-07 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170207_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='saved_articles',
            field=models.ManyToManyField(blank=True, to='articles.Article'),
        ),
    ]
