# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-29 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('website', models.URLField(max_length=250)),
                ('site_name', models.CharField(max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=250)),
                ('twitter', models.CharField(blank=True, max_length=250)),
                ('vk', models.CharField(blank=True, max_length=250)),
                ('instagram', models.CharField(blank=True, max_length=250)),
                ('main_pic', models.URLField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('auth_views', models.PositiveIntegerField(default=0)),
                ('article_views', models.PositiveIntegerField(default=0)),
                ('limitation', models.IntegerField(default=100)),
                ('slug', models.SlugField(unique=True)),
                ('randomizer', models.PositiveIntegerField()),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
