# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-03 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0002_magazine_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='auth_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
