# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-05 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0003_magazine_auth_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='site_name',
            field=models.CharField(default='blog-news.am', max_length=100),
            preserve_default=False,
        ),
    ]
